version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 'Postgres@2025'
      POSTGRES_USER: postgres
      POSTGRES_DB: chatbot
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./config/db.sql:/docker-entrypoint-initdb.d/init.sql
